# Generated by Django 6.0.5 on 2026-05-10 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('cost_index', models.FloatField(default=1.0)),
                ('popularity', models.IntegerField(default=50)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='cities/')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('sightseeing', 'Sightseeing'), ('food', 'Food'), ('adventure', 'Adventure'), ('culture', 'Culture'), ('physical', 'Physical')], max_length=20)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('duration_hours', models.FloatField()),
                ('description', models.TextField(blank=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='places.city')),
            ],
        ),
    ]
